In [ ]:
# Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its
# application.

Min-Max scaling is a method of feature scaling that transforms the values of each feature in a dataset to a range of 0 to 1.
This is done by subtracting the minimum value of each feature from all of its values, and then dividing by the difference 
between the minimum and maximum values.
Min-Max scaling is a popular technique for data preprocessing because it is simple to implement and it does not assume any 
distributional assumptions about the data. 

In [156]:
# Example of Min-Max Scaling
import seaborn as sns
df = sns.load_dataset("planets")

In [157]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [158]:
from sklearn.preprocessing import MinMaxScaler

In [159]:
min_max = MinMaxScaler()

In [160]:
min_max.fit(df[['mass','distance']])

MinMaxScaler()

In [161]:
min_max.transform(df[['mass','distance']])

array([[0.28389688, 0.00894848],
       [0.08826871, 0.00654222],
       [0.10387096, 0.00217564],
       ...,
       [       nan, 0.02031499],
       [       nan, 0.03431722],
       [       nan, 0.03043425]])

In [ ]:
# Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling?
# Provide an example to illustrate its application.
Ans.
The Unit Vector technique, also known as Unit Norm or Vector Normalization, is a feature scaling method used to scale the 
individual feature vectors to have a Euclidean norm (magnitude) of 1.On the other hand,Min-Max Scaling is a different feature
scaling technique used to transform the features into a specific range (typically between 0 and 1) by linearly scaling the data.

In [162]:
# Example of unit vector technique
import seaborn as sns 
df = sns.load_dataset("taxis")

In [163]:
df.head()

pickup             dropoff  passengers  distance  fare   tip  \
0 2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0  2.15   
1 2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0  0.00   
2 2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5  2.36   
3 2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0  6.15   
4 2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0  1.10   

   tolls  total   color      payment            pickup_zone  \
0    0.0  12.95  yellow  credit card        Lenox Hill West   
1    0.0   9.30  yellow         cash  Upper West Side South   
2    0.0  14.16  yellow  credit card          Alphabet City   
3    0.0  36.95  yellow  credit card              Hudson Sq   
4    0.0  13.40  yellow  credit card           Midtown East   

            dropoff_zone pickup_borough dropoff_borough  
0    UN/Turtle Bay South      Manhattan       Manhattan  
1  Upper West Side South      Manhattan       Manhattan  
2           West Village      Manhattan       Manhattan  
3         Yorkville West      Manhattan       Manhattan  
4         Yorkville West      Manhattan       Manhattan

In [20]:
from sklearn.preprocessing import normalize

In [19]:
df.columns

Index(['pickup', 'dropoff', 'passengers', 'distance', 'fare', 'tip', 'tolls',
       'total', 'color', 'payment', 'pickup_zone', 'dropoff_zone',
       'pickup_borough', 'dropoff_borough'],
      dtype='object')

In [25]:
normalize(df[['distance', 'fare', 'tip']])

array([[0.21346145, 0.93389384, 0.28683882],
       [0.15606402, 0.98774694, 0.        ],
       [0.1716575 , 0.93973084, 0.29570197],
       ...,
       [0.25050016, 0.96811656, 0.        ],
       [0.18349711, 0.98302025, 0.        ],
       [0.2429556 , 0.94658025, 0.21203398]])

In [29]:
import pandas as pd
pd.DataFrame(normalize(df[['distance', 'fare', 'tip']]),columns = ['distance','fare','tip'])

distance      fare       tip
0     0.213461  0.933894  0.286839
1     0.156064  0.987747  0.000000
2     0.171657  0.939731  0.295702
3     0.267899  0.939386  0.213971
4     0.231742  0.965592  0.118017
...        ...       ...       ...
6428  0.160133  0.960800  0.226322
6429  0.307453  0.951563  0.000000
6430  0.250500  0.968117  0.000000
6431  0.183497  0.983020  0.000000
6432  0.242956  0.946580  0.212034

[6433 rows x 3 columns]

In [ ]:
# Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an
# example to illustrate its application.
Ans.
PCA (Principal Component Analysis) is a widely used technique in machine learning and statistics for dimensionality 
reduction. It is primarily used to transform high-dimensional data into a lower-dimensional subspace while retaining
as much of the original datas variance as possible. 
PCA is a widely used dimensionality reduction technique. It works by finding the directions of maximum variance in the
data and projecting the data onto those directions. This reduces the dimensionality of the data while retaining as much
information as possible.

In [122]:
# Example of PCA
import numpy as np
import seaborn as sns 
df = sns.load_dataset("tips")

In [123]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [124]:
from sklearn.decomposition import PCA

In [125]:
pca = PCA(n_components=2)

In [126]:
pca.fit(df[['total_bill','tip']])

PCA(n_components=2)

In [128]:
import pandas as pd
pd.DataFrame(pca.transform(df[['total_bill','tip']]),columns = ['PC1','PC2'])

PC1       PC2
0   -2.990624 -1.681283
1   -9.534519 -0.331306
2    1.270273  0.369389
3    3.905181 -0.102053
4    4.841815  0.099977
..        ...       ...
239  9.501309  1.927221
240  7.246925 -1.775029
241  2.762241 -1.297833
242 -2.086985 -1.033258
243 -1.000114  0.108149

[244 rows x 2 columns]

In [ ]:
# Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature
# Extraction? Provide an example to illustrate this concept.
Ans.
PCA (Principal Component Analysis) and Feature Extraction are closely related concepts. In fact, PCA is one of the most 
common techniques used for feature extraction.

PCA can be used for feature extraction by projecting the original features onto a lower-dimensional space. The new features
in this lower-dimensional space are called principal components. The principal components are the directions of 
maximum variance in the data.

In [129]:
# Example of PCA
import numpy as np
import seaborn as sns 
df = sns.load_dataset("healthexp")

In [130]:
df.head()

Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [131]:
from sklearn.decomposition import PCA

In [132]:
pca = PCA(n_components=2)

In [133]:
pca.fit(df[['Spending_USD','Life_Expectancy']])

PCA(n_components=2)

In [134]:
import pandas as pd
pd.DataFrame(pca.transform(df[['Spending_USD','Life_Expectancy']]),columns = ['PC1','PC2'])

PC1       PC2
0   -2537.033278  5.115251
1   -2597.199872  3.463213
2   -2665.350106  3.704271
3   -2638.906029  3.627142
4   -2462.383047  4.879814
..           ...       ...
269  4149.645302  0.398452
270  2679.081890 -2.073416
271  2229.362415 -0.562371
272  1876.307266 -5.167724
273  9069.835916  8.753851

[274 rows x 2 columns]

In [135]:
# Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset
# contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to
# preprocess the data.

import pandas as pd

df = pd.DataFrame({'Price' : [200,300,250,150,400,300,450],
             'Rating' : [5,4,5,3,4,3,5],
             'Delivery_time' : [7,8,9,10,12,4,5]})
df.head()

Price  Rating  Delivery_time
0    200       5              7
1    300       4              8
2    250       5              9
3    150       3             10
4    400       4             12

In [136]:
from sklearn.preprocessing import MinMaxScaler

In [137]:
min_max = MinMaxScaler()

In [138]:
min_max.fit(df[['Price','Rating','Delivery_time']])

MinMaxScaler()

In [139]:
min_max.transform(df[['Price','Rating','Delivery_time']])

array([[0.16666667, 1.        , 0.375     ],
       [0.5       , 0.5       , 0.5       ],
       [0.33333333, 1.        , 0.625     ],
       [0.        , 0.        , 0.75      ],
       [0.83333333, 0.5       , 1.        ],
       [0.5       , 0.        , 0.        ],
       [1.        , 1.        , 0.125     ]])

In [140]:
# Q6. You are working on a project to build a model to predict stock prices. The dataset contains many
# features, such as company financial data and market trends. Explain how you would use PCA to reduce the
# dimensionality of the dataset.

import pandas as pd

df = pd.DataFrame({'Financial_data' : [20000,30000,40000,50000,60000,70000],
                   'Market_trends' : [250,290.5,320.8,390,420.8,500]})

In [141]:
df.head()

Financial_data  Market_trends
0           20000          250.0
1           30000          290.5
2           40000          320.8
3           50000          390.0
4           60000          420.8

In [142]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [143]:
pca = PCA(n_components=2)

In [144]:
pca.fit(df[['Financial_data','Market_trends']])

PCA(n_components=2)

In [145]:
import pandas as pd
pd.DataFrame(pca.transform(df[['Financial_data','Market_trends']]),columns=['PC1','PC2'])

PC1        PC2
0 -25000.248900 -10.133273
1 -15000.170382  -1.773348
2  -5000.141701  16.786454
3   5000.077044  -3.553279
4  15000.108168  14.506530
5  25000.375771 -15.833084

In [146]:
# Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the
# values to a range of -1 to 1.

import numpy as np
Data = np.array([1, 5, 10, 15, 20]).reshape(-1,1)

In [147]:
from sklearn.preprocessing import MinMaxScaler

In [148]:
new_min = -1
new_max = 1

In [149]:
min_max = MinMaxScaler(feature_range=(new_min,new_max))

In [150]:
min_max.fit_transform(Data)

array([[-1.        ],
       [-0.57894737],
       [-0.05263158],
       [ 0.47368421],
       [ 1.        ]])

In [151]:
# Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform
# Feature Extraction using PCA. How many principal components would you choose to retain, and why?

import pandas as pd

df = pd.DataFrame({'Height' : [120,130,140,150,160,170,150,155,145],
              'Weight' : [50,60,70,75,60,80,58,55,60],
              'Age' : [20,30,40,25,35,20,18,30,24],
              'Gender' : ['Male','Female','Male','Female','Male','Male','Female','Male','Male'],
              'Blood_pressure' : [120,90,95,100,110,115,105,125,90]})

In [152]:
df.head()

Height  Weight  Age  Gender  Blood_pressure
0     120      50   20    Male             120
1     130      60   30  Female              90
2     140      70   40    Male              95
3     150      75   25  Female             100
4     160      60   35    Male             110

In [153]:
from sklearn.decomposition import PCA

In [154]:
pca = PCA(n_components=3)

In [155]:
import pandas as pd
pd.DataFrame(pca.fit_transform(df[['Height','Weight','Blood_pressure']]),columns=['PC1','PC2','PC3'])

PC1        PC2       PC3
0 -24.276823  21.496477 -6.339691
1 -20.375799 -10.660637  0.780846
2  -6.488803 -11.762472 -4.781284
3   5.616713 -10.618440 -6.246780
4  12.022873   3.945532  6.862448
5  29.472831  -1.648039 -6.892948
6   0.986245   1.453979  5.869964
7  10.072361  20.024089  3.302179
8  -7.029598 -12.230489  7.445265